- name: Copy docker-compose file
  become: yes
  copy:
    src: "{{ docker_compose_scr  }}"
    dest: "{{ docker_compose_dsc }}"

- name: Starting deployment
  become: yes
  shell: |
    docker-compose -f /opt/nextcloud/docker-compose.yaml up -d
  args:
    executable: /bin/bash
  changed_when: false

- name: Check connection to Localhost
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    timeout: 120
  register: out
- name: print out
  debug:
    msg: "{{ out }}"

- name: Pause for install app
  pause:
    seconds: 180

- name: Check content to the site
  uri:
    url: "http://localhost"
    return_content: yes
  register: out
  failed_when: "'Nextcloud' not in out.content"
- name: Print out
  debug:
    msg: "{{ out }}"
