packages_for_docker:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

#repo_url: "https://download.docker.com/linux/ubuntu bionic stable"

source_list: /etc/apt/sources.list

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose
