- name: Stoping and delete docker containers
  shell: |
    docker-compose -f /opt/nextcloud/docker-compose.yaml down
  args:
    executable: /bin/bash
  register: stop
  become: yes
  changed_when: false
- name: Print stop
  debug:
    msg: "{{ stop.stdout_lines  }}"

- name: Remove docker images
  shell: |
    docker rmi nextcloud:19.0.5-apache
#    docker rmi mariadb:latest
  args:
    executable: /bin/bash
  register: out
- name: Print out
  debug:
    msg: "{{ out.stdout_lines  }}"

- name: Remove app dir contents
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/opt/nextcloud/app/*"

- name: Remove db dir contents
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/var/db/mysql/*"

- name: Comeback previous user and db data to home folders
  shell: |
    rsync -r /opt/backups_nextcloud/app_data/ /opt/nextcloud/app/
    rsync -r /opt/backups_nextcloud/db_data/ /var/db/mysql/
  args:
    executable: /bin/bash
  register: out
  changed_when: false
  become: yes

- name: Removing docker-compose file
  file:
    path: "{{ docker_compose_path }}"
    state: absent

- name: Return previous docker-compose file
  copy:
    src: "{{ docker_compose_scr  }}"
    dest: "{{ docker_compose_dsc }}"

- name: Starting rollback
  shell: |
    docker-compose -f /opt/nextcloud/docker-compose.yaml up -d
  args:
    executable: /bin/bash
  register: start
  become: yes

- name: Check connection to Localhost
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    timeout: 120
  register: out
- name: print out
  debug:
    msg: "{{ out }}"

- name: Pause for runing app
  pause:
    seconds: 150

- name: Check content to the site
  uri:
    url: "http://localhost"
    return_content: yes
  register: out
  failed_when: "'Nextcloud' not in out.content"
- name: Print out
  debug:
    msg: "{{ out }}"

- name: Notify in Slack if update app is failure
  slack:
    username: 'Ansible sender'
    color: good
    icon_url: https://logos-download.com/wp-content/uploads/2016/10/Ansible_log$
    token: "TFBPBNB2L/B01FX4HAAG0/is8cXkDDVTLq7ItJKM6rWJ7X"
    channel: "#ci_cd_test"
    msg: "Rollback complete"
