- name: Stoping and delete docker containers
  shell: |
    docker-compose -f /opt/nextcloud/docker-compose.yaml down
  args:
    executable: /bin/bash
  register: stop
  become: yes
- name: Print stop
  debug:
    msg: "{{ stop.stdout_lines  }}"

- name: Remove docker images
  shell: |
    docker rmi nextcloud
    docker rmi mysql
  args:
    executable: /bin/bash
  register: out
- name: Print out
  debug:
    msg: "{{ out.stdout_lines  }}"

- name: Removing docker-compose file
  file:
    path: "{{ docker_compose_path }}"
    state: absent

- name: Return docker-compose file
  copy:
    src: "{{ docker_compose_scr  }}"
    dest: "{{ docker_compose_dsc }}"

- name: Starting rollback
  shell: |
    docker-compose -f /opt/nextcloud/docker-compose.yaml up -d
  args:
    executable: /bin/bash
  register: start
  become: yes

- name: Check connection to Localhost
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    timeout: 120
  register: out
- name: print out
  debug:
    msg: "{{ out }}"

- name: Pause for runing app
  pause:
    seconds: 30

- name: Check content to the site
  uri:
    url: "http://localhost"
    return_content: yes
  register: out
  failed_when: "'Nextcloud' not in out.content"
- name: Print out
  debug:
    msg: "{{ out }}"

