- name: Stoping and delete docker containers
  shell: |
    docker-compose -f /opt/nextcloud/docker-compose.yaml down
  args:
    executable: /bin/bash
  register: stop
  changed_when: false

- name: Remove docker images
  shell: |
    docker rmi nextcloud:19.0.5-apache
    docker rmi mariadb:latest
  args:
    executable: /bin/bash
  register: out
- name: Print out
  debug:
    msg: "{{ out.stdout_lines  }}"

- name: Remove app dir contents
  become: yes
  file:
    path: "/opt/nextcloud/app/"
    state: absent
  with_fileglob:
    - "/opt/nextcloud/app/*"

- name: Remove db dir contents
  become: yes
  file:
    path: "/var/db/mysql/"
    state: absent
  with_fileglob:
    - "/var/db/mysql/*"

- name: Comeback previous contents to home folders
  shell: |
    rsync -a /opt/backups_nextcloud/app_data/ /opt/nextcloud/app/
    rsync -a /opt/backups_nextcloud/db_data/ /var/db/mysql/
  args:
    executable: /bin/bash
  register: out
  changed_when: false

- name: Removing docker-compose file
  file:
    path: "{{ docker_compose_path }}"
    state: absent

- name: Return previous docker-compose file
  copy:
    src: "{{ docker_compose_scr  }}"
    dest: "{{ docker_compose_dsc }}"

- name: Starting rollback
  shell: |
    docker-compose -f /opt/nextcloud/docker-compose.yaml up -d
  args:
    executable: /bin/bash
  register: start

- name: Check connection to Localhost
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    timeout: 120
  register: out
- name: print out
  debug:
    msg: "{{ out }}"

- name: Pause for runing app
  pause:
    seconds: 180

- name: Check content to the site
  uri:
    url: "http://localhost"
    return_content: yes
  register: out
  failed_when: "'Nextcloud' not in out.content"
- name: Print out
  debug:
    msg: "{{ out }}"

- name: Notify in Slack if rollback complete
  slack:
    username: 'Ansible sender'
    color: good
    icon_url: https://logos-download.com/wp-content/uploads/2016/10/Ansible_log$
    token: "{{ slack_token }}"
    channel: "#ci_cd_test"
    msg: "Rollback complete"
