docker_compose_scr: ./roles/deploy/files/docker-compose.yaml

docker_compose_dsc: /opt/nextcloud/

source_app_dir: /opt/nextcloud/app

sync_app_dir: /opt/backups_nextcloud/app_data

source_db_dir: /var/db/mysql/

sync_db_dir: /opt/backups_nextcloud/db_data

docker_compose_path: /opt/nextcloud/docker-compose.yaml
