- name: Install packages for Docker
  apt:
    name: "{{ packages_for_docker }}"
    state: present
  become: yes

- name: Add GPG key and repo
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  args:
    executable: /bin/bash
  become: yes
  changed_when: false

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
  become: yes

- name: Add user to docker group and delegate priviliges
  shell: |
    usermod -aG docker jenkins
    chown jenkins /var/run/docker.sock
  args:
    executable: /bin/bash
  changed_when: false
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
