version: '3.5'
services:
  nextcloud-app:
    image: nextcloud:19.0.4-apache
    container_name: nextcloud
    networks:
      - cloud
    depends_on:
      - mysql
    ports:
      - 80:80
    volumes:
      - /opt/nextcloud/app/html:/var/www/html
      - /opt/nextcloud/app/config:/var/www/html/config
      - /opt/nextcloud/app/custom_apps:/var/www/html/custom_apps
      - /opt/nextcloud/app/data:/var/www/html/data:rw
      - /opt/nextcloud/app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=mysql
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    restart: unless-stopped

  mysql:
    image: mariadb:latest
    container_name: mysql
    networks:
      - cloud
    volumes:
      - /var/db/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
networks:
  cloud:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
